//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessSystem_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentChild
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommentChild()
        {
            this.CommentGrandchilds = new HashSet<CommentGrandchild>();
            this.Replies = new HashSet<Reply>();
        }
    
        public int CommentTypeID { get; set; }
        public string CommentTypeName { get; set; }
        public Nullable<int> CommentID { get; set; }
        public string Question { get; set; }
        public Nullable<System.DateTime> SentTime { get; set; }
        public Nullable<int> ActivityMainID { get; set; }
    
        public virtual ActivitiesMain ActivitiesMain { get; set; }
        public virtual CommentMain CommentMain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentGrandchild> CommentGrandchilds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reply> Replies { get; set; }
    }
}
