//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIPBussinessSystem_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RequisitionMain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequisitionMain()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }

        [Display(Name = "表單編號")]
        public int OrderID { get; set; }

        public Nullable<int> ReportID { get; set; }

        [Display(Name = "員工編號")]
        public Nullable<int> EmployeeID { get; set; }

        [Display(Name = "請購日期")]
        public Nullable<System.DateTime> RequisitionDate { get; set; }
        public Nullable<int> ApprovalStatusID { get; set; }
    
        public virtual ApprovalStatu ApprovalStatu { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ReportCategory ReportCategory { get; set; }
    }
}
