//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessSystemMVC_Admin_page_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeApprovalTemp
    {
        public int ID { get; set; }
        public string EmployeeName { get; set; }
        public string Gender { get; set; }
        public System.DateTime Birth { get; set; }
        public System.DateTime HireDate { get; set; }
        public string Account { get; set; }
        public int OfficeID { get; set; }
        public int DepartmentID { get; set; }
        public int PositionID { get; set; }
        public int ManagerID { get; set; }
        public bool Employed { get; set; }
        public int GroupID { get; set; }
        public string Photo { get; set; }
        public string CreateOrUpdate { get; set; }
        public int Editor { get; set; }
        public System.DateTime EditorTime { get; set; }
        public Nullable<int> GroupLeaderID { get; set; }
        public Nullable<System.DateTime> GroupLeaderSignTime { get; set; }
        public Nullable<int> DepartmentLeaderID { get; set; }
        public Nullable<System.DateTime> DepartmentLeaderSignTime { get; set; }
        public bool SignState { get; set; }
    
        public virtual Employee EmployeebyEditor { get; set; }
        public virtual Employee EmployeebyGroupLeader { get; set; }
        public virtual Employee EmployeebyDepartmentLeader { get; set; }
    }
}
